steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/github.com/cloud-native-web-development/support-services-gumroad-github-access:$COMMIT_SHA",
        ".",
      ]
  # push the container image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "gcr.io/$PROJECT_ID/github.com/cloud-native-web-development/support-services-gumroad-github-access:$COMMIT_SHA",
      ]
  # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "gumroad-github-access"
      - "--image"
      - "gcr.io/$PROJECT_ID/github.com/cloud-native-web-development/support-services-gumroad-github-access:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
images:
  - "gcr.io/$PROJECT_ID/github.com/cloud-native-web-development/support-services-gumroad-github-access:$COMMIT_SHA"
